### ISSUE TITLE
secondSpace in LocationSearchTable

### ISSUE THREAD

**Issue by PVKonovalov** [Faryn/CycleMaps#2]
Hi!
Because the "second space" located between "locality" and "administrativeArea" I think that line 26 in LocationSearchTable.swift should like as  

let secondSpace = (selectedItem.locality != nil && selectedItem.administrativeArea != nil) ? " " : ""

**Comment by Faryn** [comment]
Thank you for the report! I don't think it changes much in the search but you're right it's inconsistent.
