### ISSUE TITLE
Titles for annotations in iOS 13

### ISSUE THREAD

**Issue by PVKonovalov** [Faryn/CycleMaps#3]
Titles for annotations for GPX's "Start" and "Destination" points have disappeared in iOS 13.1 and Xcode 11 for all maps styles except Apple Maps.

**Comment by PVKonovalov** [comment]
@sandammeer has opened a Thread on the Apple Developer Forums regarding such issue, you can follow it here: https://forums.developer.apple.com/message/387246#387246

**Comment by Faryn** [comment]
Thank you for the research. I tried a few different things with the Overlays but it doesn't seem to work. Guess I'll wait and hope for a fix from Apple.

**Comment by PVKonovalov** [comment]
Wow! It's fixed at least in version 13.5.1

**Comment by Faryn** [comment]
Great, thank you for the feedback. Closing the issue.
